### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by ivlevdenis**
And fixed some strings

### CODE REVIEW

**Comment by ad-m** [comment]
I like fixes on multiple languages. However, I am not able to review the linguistic elements - I do not know Russian.

**Comment by ivlevdenis** [comment]
All errors and strage typos fixed.

**Comment by ad-m** [comment]
I suggest that we wait for someone who knows Russian too.

**Comment by malinoff** [comment]
@ad-m 00c21dd was made after my review. Everything else looks good to me.

**Comment by ad-m** [comment]
I trust you. Merged! =) 

I will try to prepare a translation for Polish language in days.

**Pull request merged**
