### PR TITLE
Fix get_new_mail admin action.

### PR DESCRIPTION
**Pull request by Gerhut**
Mailbox.get_new_mail returns a generator that does not actually run if we do not iterate it.

### CODE REVIEW

**Comment by ad-m** [comment]
Could you add tests for that to avoid regression in future?

**Comment by Gerhut** [comment]
Sure, trying

**Comment by Gerhut** [comment]
The difficulty is that to test something requires the `django.contrib.admin` app, we have to introduce lots of dependencies that are different in different Django versions.

**Comment by modernNeo** [comment]
any ideas on when this will get merged? its a pretty big blocker. @ad-m

**Pull request merged**
