### PR TITLE
Fix text content with text attachment

### PR DESCRIPTION
**Pull request by ad-m**
I identified the test case for #169.

@dborin, thank you for your support. Now I can eliminate him.

### CODE REVIEW

**Comment by coddingtonbear** [comment]
Yep; I'm hoping to get to it sometime in the next day or so, @dborin.

**Comment by dborin** [comment]
Thank you so much for the fast turn-around.  Much appreciated.

**Comment by dborin** [comment]
@ad-m If you have time, it would be great to get this merged.  Thanks in advance.

**Comment by coddingtonbear** [comment]
@ad-m is in Poland, so it might be a while before he's up and ready to tackle that kind of thing, and although I'm in Portland, I'm still at work for the next few hours.  That said, I'll try find a few minutes to push up new build after work today.

From the sounds of it, it sounds like you guys might not have a process for packing-up python packages from a fork?

**Comment by dborin** [comment]
Yeah, they're not gonna want to get this from a fork.  We can wait a few
hours, to be sure.

Thanks again.

**Comment by coddingtonbear** [comment]
I'm sure you know this, but just in case -- if you're using Python packages in any sort of production environment, it's solidly recommended that you make the effort to set up your own package index.  You never know when people might delete packages that you depend upon, or when a security pre-release notification might end up in your inbox requiring a manual package build.  I totally understand not wanting to build one for _this_ sort of thing, but if you don't have something like that in place in your infrastructure, there are tons of tools solving that kind of problem, and you should check them out.

Regarding doing this release, I'll probably find time to do this sometime after 6p today, though, and'll post something here when it's built.

**Comment by coddingtonbear** [comment]
Released as part of 4.7.1

**Comment by dborin** [comment]
Just installed 4.7.1 and it's working great.  Thanks so much for doing that
so quickly.

**Pull request merged**
