### PR TITLE
Use django build-in test runner

### PR DESCRIPTION
**Pull request by ad-m**
@coddingtonbear , why do you use ``py.test``? It is problematic. See https://github.com/coddingtonbear/django-mailbox/pull/142 .

### CODE REVIEW

**Comment by ad-m** [comment]
I drop Django 1.5. It failing. I don't see any reason to do any activities to support too old Django versions.

**Comment by ivlevdenis** [comment]
I fix starts of tests, but some test not passed. https://travis-ci.org/ivlevdenis/django-mailbox

**Comment by ad-m** [comment]
@ivlevdenis , fixed on master.

**Comment by ivlevdenis** [comment]
@ad-m, tada https://gist.github.com/ivlevdenis/e8cdbe748b1cc752964dc293e279df41 :)

**Pull request merged**
