### PR TITLE
Add tests docs to CI and fix docs warning

### PR DESCRIPTION
**Pull request by ad-m**
@modernNeo, could you take a look?

### CODE REVIEW

**Comment by modernNeo** [comment]
@ad-m not sure I can be of much help. I am still very much a beginner with things like travisCI and tox :sweat_smile:

**Comment by ad-m** [comment]
Hmm.. Build started, but no GitHub checks :-/ https://travis-ci.org/github/coddingtonbear/django-mailbox/builds/735556509

**Comment by coddingtonbear** [comment]
Looking at the build, it looks like it's for some reason not able to build docs when running; are we sure that's the correct command to execute?

**Comment by ad-m** [comment]
Please notice"make docs clean"? It is removed tight after finishing

**Comment by coddingtonbear** [comment]
All fixed: https://travis-ci.org/github/coddingtonbear/django-mailbox/builds/748031568

**Pull request merged**
