### PR TITLE
Imap folders

### PR DESCRIPTION
**Pull request by dmippoltiov**
I made a few changes that allow django_mailbox to work with imap folders:
1) transoport/imap.py . Now ImapTransport have additional initial param "folder". When it is defined django_mailbox fetch new mail from this folder instead of inbox.
2) Added @property folder to class Mailbox. Using this property you can parse folder name from mailbox uri: 
for example: imap://user:password@server.tld/folder=FOLDER_NAME&archive=ARCHIVE_NAME . Folder value is passed into get_connection function when you use imap protocol .

### CODE REVIEW

**Comment by coddingtonbear** [comment]
Nicely done!  This looks pretty great; could I convince you into updating the 'POP3 and IMAP Mailboxes' section of [`docs/topics/mailbox_types.rst`](https://github.com/coddingtonbear/django-mailbox/blob/master/docs/topics/mailbox_types.rst) to include this documentation as part of this pull request?

**Comment by dmippoltiov** [comment]
Done. Please check English after me, I am not sure everything is ok.

**Comment by coddingtonbear** [comment]
Только если ты не высмеивать мои россии, @dmippoltiov ;-)

**Comment by dmippoltiov** [comment]
Хорошо :-)

**Pull request merged**
