### PR TITLE
Add blank option to eml field, fixes admin

### LINKED ISSUE #150: Cannot save message in django admin with empty eml field
Love django-mailbox.  Came across some unexpected behavior, though.  In the django admin, you cannot save a message if the eml ("Raw message contents") field is empty.  It is a nullable field but required in the admin.  Granted, this is likely a fringe use case, but it can be fixed by adding the "blank=True" option to the eml field in the Message model.  That is, change this:

    eml = models.FileField(
        _(u'Raw message contents'),
        null=True,
        upload_to="messages",
        help_text=_(u'Original full content of message')
    )

to this:

    eml = models.FileField(
        _(u'Raw message contents'),
        null=True,
        blank=True,
        upload_to="messages",
        help_text=_(u'Original full content of message')
    )

I can create a pull request if necessary.

Thanks for all your work on this!

### PR DESCRIPTION
**Pull request by cleonello**
fixes #150 

Note, did not add migrations in this commit because of possible discrepancy.  Can create a separate commit/pull request with those if desired.

### CODE REVIEW

**Comment by ad-m** [comment]
What possible discrepancy do you mean?

**Comment by ad-m** [comment]
I did not pay attention to the earlier reported issue. 

@cleonello , do you can add migrations?

**Comment by ad-m** [comment]
@cleonello , do you have any time to work on it? Just ```python manage.py makemigrations && git commit".

**Comment by pfouque** [comment]
Superseded by #282

**Pull request closed without merging**
