### PR TITLE
Fix parse UTF-8 filename attachment - close #104

### LINKED ISSUE #104: Fail to parse message due encoding
Redacted fail message:
```
Return-path: <SRS0=9Ddk64=SW=REDACTED=kontakt@porady.REDACTED>
Envelope-to: porady@REDACTED
Delivery-date: Thu, 30 Jun 2016 12:52:33 +0200
Received: from s33.linuxpl.com ([88.198.46.46])
	by s50.hekko.net.pl with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <kontakt@REDACTED>)
	id 1bIZaC-0000Cx-W0
	for porady@REDACTED; Thu, 30 Jun 2016 12:52:33 +0200
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=REDACTED;
	 s=x; h=Message-ID:Subject:To:From:Date:Content-Type:MIME-Version:Sender:
	Reply-To:Cc:Content-Transfer-Encoding:Content-ID:Content-Description:
	Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:
	In-Reply-To:References:List-Id:List-Help:List-Unsubscribe:List-Subscribe:
	List-Post:List-Owner:List-Archive;
	bh=eC6KQaY8pKyVa/Khy6mQZxec1jahvFvFLPhOXQzPCog=; b=feFwok/UGXcCZdptybFLrf7myS
	EtomJXxQiSpkNmMU71L/uLtg6YAlmLQHtyT7Vz+r/ZmHg/eSPjL7S7k6Bm+gzduyO5xy24mVfAceL
	lEteTnLfZhgqbrarMBM4vySplozca8GBZ4/2lR+hNALNnyhkmAs9iMo7D6K2Ykd5s7RzyCFRaS4JI
	m4jXXeUTDmB/TJgrcQNaIuXH7xz/BgxQpnc1zPsf90ScJAQrGgOXPSSNnLTp58q143XByCSB790ib
	U3TR2zfGFojjxdIlDnpMKjwO/w3DHP6prmBODozBlklGqpLbZyehOaclxSo35IIZTqk7MYtLt9tyy
	lHzMX3hg==;
Received: from [127.0.0.1] (helo=s33.linuxpl.com)
	by s33.linuxpl.com with esmtpa (Exim 4.87)
	(envelope-from <kontakt@REDACTED>)
	id 1bIZaB-0002KZ-Lq
	for porady@REDACTED; Thu, 30 Jun 2016 12:52:31 +0200
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="=_23825343e9a28de91c2eec59d6c7d4bf"
Date: Thu, 30 Jun 2016 12:52:31 +0200
From: Kontakt <kontakt@REDACTED>
To: porady@REDACTED
Subject: =?UTF-8?Q?Odpowied=C5=BA_od_burmistrza_na_wniosek_stowarzyszenia?=
Organization: VE-TO
Message-ID: <8cd4a49b11cf9a1867432bd5909a06bb@REDACTED>
X-Sender: kontakt@REDACTED
User-Agent: Roundcube Webmail/1.1.4
X-HEKKO: 88.198.46.46:

--=_23825343e9a28de91c2eec59d6c7d4bf
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8;
 format=flowed

REDACTED
------------------------------------------------------------------------------------
Niniejsza wiadomość elektroniczna [lub jej załączniki] może zawierać 
poufne lub chronione prawem informacje, które przeznaczone są wyłącznie 
dla adresata tej wiadomości.
Należy dołożyć należytej staranności w celu nie ujawniania ich osobom 
trzecim.
--=_23825343e9a28de91c2eec59d6c7d4bf
Content-Transfer-Encoding: base64
Content-Type: image/jpeg;
 name="=?UTF-8?Q?pi=C5=82kochwyty=2Ejpg?="
Content-Disposition: attachment;
 filename*=UTF-8''pi%C5%82kochwyty.jpg;
 size=465813

UkVEQUNURUQK
--=_23825343e9a28de91c2eec59d6c7d4bf
Content-Transfer-Encoding: base64
Content-Type: image/jpeg;
 name="=?UTF-8?Q?odpowied=C5=BA_Burmistrza=2Ejpg?="
Content-Disposition: attachment;
 filename*=UTF-8''odpowied%C5%BA%20Burmistrza.jpg;
 size=544348

UkVEQUNURUQK
--=_23825343e9a28de91c2eec59d6c7d4bf--
```

Example stack trace:
```
ERROR: test_utf8_message (letters.tests.test_models.ReceiveEmailTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adas/Devel/poradnia/poradnia/letters/tests/test_models.py", line 163, in test_utf8_message
    message = self.get_message('utf8_message.eml')
  File "/home/adas/Devel/poradnia/poradnia/letters/tests/test_models.py", line 126, in get_message
    msg = self.mailbox._process_message(message)
  File "/home/adas/Devel/poradnia/django_mailbox/models.py", line 354, in _process_message
    message = self._get_dehydrated_message(message, msg)
  File "/home/adas/Devel/poradnia/django_mailbox/models.py", line 240, in _get_dehydrated_message
    self._get_dehydrated_message(part, record)
  File "/home/adas/Devel/poradnia/django_mailbox/models.py", line 266, in _get_dehydrated_message
    filename = utils.convert_header_to_unicode(raw_filename)
  File "/home/adas/Devel/poradnia/django_mailbox/utils.py", line 80, in convert_header_to_unicode
    ) for bytestr, encoding in email.header.decode_header(header)
  File "/usr/lib/python2.7/email/header.py", line 73, in decode_header
    header = str(header)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 2: ordinal not in range(128)
````

Python 2.7 & django_mailbox 4.5.3

### PR DESCRIPTION
**Pull request by ad-m**
Hello,

 In wild I meet message which make django_mailbox fail to parse (see #104), so prepared fix for them.

I  am not sure it is a good way, but...it works and all tests pass.

Greetings,

### CODE REVIEW

**Comment by ad-m** [comment]
I don't want use fork of project, but this error occurs again in the wild

**Comment by coddingtonbear** [comment]
Hrm -- sorry about that, I hadn't noticed this PR; I'll have a look at it tonight.

**Comment by ad-m** [comment]
Thank you. 

It might be interesting to your @coddingtonbear . I use your project in github.com/watchdogpolska/poradnia application. In was running at poradnia.siecobywatelska.pl for Citizens Network Watchdog Poland. We give advice in the area of the right to information and receive emails with questions for people. 

Citizens Network Watchdog Poland is an independent, apolitical and non-profit organization in the form of a watchdog and think-do-thank organization for the public benefit. Over the last twelve years we have been working for transparency in the public realm, good government and the accountability of power in Poland.

We defend the right to information. We regard it not only as the condition of a good state but above all, as an inviolable human right which safeguards human dignity, allows freedom of expression and ensures protection from the abuse of power. We are empowering citizens to feel that they have the right to find out how government and state institutions function as well as influence decision-making and the management of public assets (such as taxpayers money). We provide legal advice as well as teach how to act effectively in situations where state institutions do not respect citizens’ rights.

Over the years we have built up a sound knowledge on the topic of access to public information, civil control and common decision-making by citizens in public matters. Providing legal advice has given us the opportunity to get to know closely thousands of specific cases as well as having participated in judicial proceedings — a significant number of which we have won.

**Comment by coddingtonbear** [comment]
Released as part of 4.5.4; sorry about that -- I had no idea that this PR existed until you posted your message earlier.  I should really pay a little bit more attention to my github notifications.

It's awesome to me that you are helping to improve government accountability and provide people with a resource they can use for getting help in the event that their rights are being infringed upon.       I often find myself thinking about ways I can contribute to similarly-charitable organizations in my own country, but usually just default to taking the easy route and just donating money.  Thanks for letting me know what you're using this for and letting me feel like I'm helping you (in some very, very, very small way) do good.

Incidentally -- *thank* *you* ***so*** *much* for posting a test case for this; that makes it fantastically easier to review and helps me know that I won't break that behavior again in the future.

Cheers, and I'll be sure to pay a little closer attention when you next post a PR.

**Pull request merged**
