### PR TITLE
possible fix for python3 maildir issue

### PR DESCRIPTION
**Pull request by leifurhauks**
possible fix for issue #58

### CODE REVIEW

**Comment by leifurhauks** [comment]
I didn't realize I needed to supply the environment variables to Travis, sorry about that!

**Comment by coddingtonbear** [comment]
Oh, you don't have to!  It's just complaining because it couldn't run the integration tests for your PR since I'm using their 'secure environment variables' feature to pass-in account information, and Travis doesn't provide those for PRs.

TLDR; this is all my fault, I should either make the test suite automatically skip the integration tests for PRs, or tell Travis not to run tests for PRs.

**Comment by coddingtonbear** [comment]
Looks perfect!  Thanks for the submission, @leifurhauks!

**Comment by coddingtonbear** [comment]
Merged via 55be6b37f23a0693eb65e9561bd1f37819d55b77 & released in v4.4.3.

**Pull request closed without merging**
