### PR TITLE
Remove null=True for Mailbox.uri and Mailbox.from_email

### PR DESCRIPTION
**Pull request by CylonOven**
According to Django's docs it's advised to not use null for string fields.

### CODE REVIEW

**Comment by coddingtonbear** [comment]
I'm a little curious, @CylonOven, is there a specific problem you ran into with the model fields set this way?

**Comment by CylonOven** [comment]
Yes, we're wanting to use your application inside a lino site. [lino-framework](http://lino-framework.org/about/what.html)
Lino doesn't accept char-fields with null. We have a work-around using our own NullCharField, but I think this solution should also work.  

Is there some reason you chose to have null/None be the default rather than an empty string?

**Comment by coddingtonbear** [comment]
Oh, no, no reason.  Setting `null=True` is definitely wrong, but I had assumed it was relatively harmless -- it's just an error I introduced five years ago when adding that field, and changing it is difficult.

I'm really afraid of springing schema migrations upon people without doing a major version bump  because I don't know which database engines will require a table re-write for a change of a field's nullability.  That said, I've recently opened up a branch into which I'm moving changes that will require a major version bump; would you mind if I just merged this into there rather than moving it into master?

**Comment by CylonOven** [comment]
That's understandable. Go right ahead.

**Comment by coddingtonbear** [comment]
I was just about to merge this PR into the `v5` branch, but it looks like you've updated your branch to rely upon a third-party library -- `lino`; I think that's probably because you posted this PR from your remote's `master` branch and have continued work there.  For the moment, I'm just going to plan on making changes similar to what you had originally written as part of the work on the `v5` branch -- there are several other database-related changes that I'm going to be making anyway.

Thanks for your contribution, @CylonOven; cheers!

**Pull request closed without merging**
