### PR TITLE
Silence pip warning

### PR DESCRIPTION
**Pull request by jonashaag**
DON'T MERGE YET! Follow up to #78

### CODE REVIEW

**Comment by jonashaag** [comment]
This PR shows some build failures with some Python/Django configurations that should actually be supported.

**Comment by jonashaag** [comment]
Looks like encoding/decoding fun

**Comment by coddingtonbear** [comment]
Hmm; the encoding error you see is expected on Python 3 due to some conflicts between Python 3's "unicode first" philosophy and the fact that the spec for what we call e-mail being something like 35 years old; there's a little bit of code in there for causing those specific tests to mark themselves as "skipped".  If you're curious, check out the line "Here are the major differences between email version 5.0 and version 4:" in [the 'email' library's docs](https://docs.python.org/3/library/email.html).

The test failure for `test_message_reply`, though, is a surprise; I'm not sure I'll have a chance to look into it for a few days, though, I'm afraid.

**Comment by jonashaag** [comment]
Hm, can't reproduce locally, maybe this has something do to with message ids (maybe they contain UTF 8 characters on Travis?). Testing now.

**Comment by jonashaag** [comment]
Looks like message-id sometimes has `\n` prepended

**Comment by jonashaag** [comment]
Indeed.

```py
# Content of the In-Reply-To header
'\n <20160119165724.1966.22261@testing-gce-7549113f-7f83-4272-a994-bc68991cd7b7.c.eco-emissary-99515.internal>'

# List of messages stored in database
['<20160119165724.1966.22261@testing-gce-7549113f-7f83-4272-a994-bc68991cd7b7.c.eco-emissary-99515.internal>', '\n <20160119165724.1966.24818@testing-gce-7549113f-7f83-4272-a994-bc68991cd7b7.c.eco-emissary-99515.internal>']
```

Do have any clue where the leading `\n ` comes from in the header? Is this even legal in the `email` lib?

**Comment by coddingtonbear** [comment]
OH MY GOD, @jonashaag, I'm terribly sorry; I totally lost track of this issue.   I'm afraid I have no idea where the newline came from in those test results, but I just pushed this up under a different branch name, and everything went just fine.  

I think we can write that off as a fluke.

**Comment by jonashaag** [comment]
> but I just pushed this up under a different branch name, and everything went just fine.

WTF

**Comment by ad-m** [comment]
Lack of activity, conflict with the branch. I close. Feel free to report again after making changes if the problem persists.

**Pull request closed without merging**
