### PR TITLE
compatibility w django 4.0

### PR DESCRIPTION
**Pull request by sanderroosendaal**

### CODE REVIEW

**Comment by ad-m** [comment]
To achieve Django 4.0 compatibility it is required to at least:

- update classifiers in setup.py
- update CI to tests on Django 4.0
- update docs to mark Django 4.0 compatibility
- verify if there is any pending migrations
- update release note to mark Django 4.0
- fix any failing tests after CI update

This is additional work (going beyond the original problem, but falling within the scope of the PR title), but it will ensure that there are no other problems and you will not have to come back.

**Comment by sanderroosendaal** [comment]
> To achieve Django 4.0 compatibility it is required to at least:
> 
> * update classifiers in setup.py
> * update CI to tests on Django 4.0
> * update docs to mark Django 4.0 compatibility
> * verify if there is any pending migrations
> * update release note to mark Django 4.0
> * fix any failing tests after CI update
> 
> This is additional work (going beyond the original problem, but falling within the scope of the PR title), but it will ensure that there are no other problems and you will not have to come back.

I completely understand and agree. However, I am not able to invest time to get up to speed with how this library works. I was just a happy user, but I have also found that I am having less and less use for it in my project. In fact, I can remove django-mailbox from my project in about an hour of work, including testing. So, the rational choice for me is to do that, although I hate to leave the work to the django-mailbox team. Thanks for years of use without issues!

**Review by Haakonoeyen — APPROVED** [review]

**Comment by Haakonoeyen** [comment]
Hi, @janetatomas11.
Could you simply use the PR in your project? I don't have write permission here, so I won't be able to help. However, I made local changes to make it work on my Django 4 project. It seems the changes I made are present in this PR.

**Comment by eugapx** [comment]
@coddingtonbear Could you please merge this? Now library incompatible with Django 4.1, cannot use it for the new projects.

**Comment by coddingtonbear** [comment]
I wish I could, @eugapx, but as discussed here: https://github.com/coddingtonbear/django-mailbox/pull/253#issuecomment-1329509623 I need some contributors to take some time to vet these changes (or the ones in the other PR referenced there).

**Review by ptav — APPROVED** [review]

**Pull request closed without merging**
