### PR TITLE
add DJANGO_MAILBOX_ATTACHMENT_UPLOAD_TO setting

### PR DESCRIPTION
**Pull request by eupharis**
Added new setting and a (fairly silly) new test.

### CODE REVIEW

**Comment by eupharis** [comment]
Oh Travis. Tests pass locally.

**Comment by coddingtonbear** [comment]
Oh, yeah, sorry -- I should really fix this up so that it doesn't require that the integration tests be runnable for PRs.  I'll have a look at this later!

**Comment by coddingtonbear** [comment]
Wow; well done @eupharis.  It has been a really long time since I last merged a PR without thinking about changes I'd like to make.

Thanks for the patch!

**Comment by eupharis** [comment]
@coddingtonbear Cheers!

**Pull request merged**
